// <auto-generated />
using System;
using CowRation.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CowRation.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190616172328_TaskTable")]
    partial class TaskTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CowRation.API.Models.CatalogIndexFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Limitation");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CatalogIndexFoods");
                });

            modelBuilder.Entity("CowRation.API.Models.CharacterizationIndexFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CatalogIndexFoodId");

                    b.Property<int>("KormId");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CatalogIndexFoodId");

                    b.HasIndex("KormId");

                    b.ToTable("CharacterizationIndexFoods");
                });

            modelBuilder.Entity("CowRation.API.Models.Korm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Korms");
                });

            modelBuilder.Entity("CowRation.API.Models.KormStorage", b =>
                {
                    b.Property<int>("KormId");

                    b.Property<int>("StorageId");

                    b.Property<double>("FoodValue");

                    b.HasKey("KormId", "StorageId");

                    b.HasIndex("StorageId");

                    b.ToTable("KormStorage");
                });

            modelBuilder.Entity("CowRation.API.Models.KormUser", b =>
                {
                    b.Property<int>("KormId");

                    b.Property<int>("UserId");

                    b.HasKey("KormId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("KormUser");
                });

            modelBuilder.Entity("CowRation.API.Models.Laboratory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CatalogIndexFoodId");

                    b.Property<int>("LaboratoryIndexFoodId");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CatalogIndexFoodId");

                    b.HasIndex("LaboratoryIndexFoodId");

                    b.ToTable("Laboratories");
                });

            modelBuilder.Entity("CowRation.API.Models.LaboratoryIndexFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KormId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("KormId");

                    b.HasIndex("UserId");

                    b.ToTable("LaboratoryIndexFoods");
                });

            modelBuilder.Entity("CowRation.API.Models.Ration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KormId");

                    b.Property<int>("TaskId");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.HasIndex("KormId");

                    b.HasIndex("TaskId");

                    b.ToTable("Rations");
                });

            modelBuilder.Entity("CowRation.API.Models.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("CowRation.API.Models.TaskRation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TaskRations");
                });

            modelBuilder.Entity("CowRation.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CowCount");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Role");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FeedingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Fat");

                    b.Property<double>("Protein");

                    b.Property<double>("Udoy");

                    b.Property<int>("UserId");

                    b.Property<double>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("FeedingCategories");
                });

            modelBuilder.Entity("CowRation.API.Models.CharacterizationIndexFood", b =>
                {
                    b.HasOne("CowRation.API.Models.CatalogIndexFood", "CatalogIndexFood")
                        .WithMany()
                        .HasForeignKey("CatalogIndexFoodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CowRation.API.Models.Korm", "Korm")
                        .WithMany()
                        .HasForeignKey("KormId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CowRation.API.Models.KormStorage", b =>
                {
                    b.HasOne("CowRation.API.Models.Korm", "Korm")
                        .WithMany("KormStorages")
                        .HasForeignKey("KormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CowRation.API.Models.Storage", "Storage")
                        .WithMany("KormStorages")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CowRation.API.Models.KormUser", b =>
                {
                    b.HasOne("CowRation.API.Models.Korm", "Korm")
                        .WithMany("KormUsers")
                        .HasForeignKey("KormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CowRation.API.Models.User", "User")
                        .WithMany("KormUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CowRation.API.Models.Laboratory", b =>
                {
                    b.HasOne("CowRation.API.Models.CatalogIndexFood", "CatalogIndexFood")
                        .WithMany()
                        .HasForeignKey("CatalogIndexFoodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CowRation.API.Models.LaboratoryIndexFood", "LaboratoryIndexFood")
                        .WithMany("Laboratories")
                        .HasForeignKey("LaboratoryIndexFoodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CowRation.API.Models.LaboratoryIndexFood", b =>
                {
                    b.HasOne("CowRation.API.Models.Korm", "Korm")
                        .WithMany()
                        .HasForeignKey("KormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CowRation.API.Models.User", "User")
                        .WithMany("LaboratoryIndexFoods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CowRation.API.Models.Ration", b =>
                {
                    b.HasOne("CowRation.API.Models.Korm", "Korm")
                        .WithMany()
                        .HasForeignKey("KormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CowRation.API.Models.TaskRation", "Task")
                        .WithMany("Rations")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CowRation.API.Models.Storage", b =>
                {
                    b.HasOne("CowRation.API.Models.User", "User")
                        .WithOne("Storage")
                        .HasForeignKey("CowRation.API.Models.Storage", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CowRation.API.Models.TaskRation", b =>
                {
                    b.HasOne("CowRation.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FeedingCategory", b =>
                {
                    b.HasOne("CowRation.API.Models.User", "User")
                        .WithOne("FeedingCategory")
                        .HasForeignKey("FeedingCategory", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
